cadastro/urls.py
from django.urls import path
from cadastro.views import UnidadeListView, UnidadeCreateView, \
    UnidadeUpdateView, UnidadeDeleteView, MarcaListView, MarcaCreateView, MarcaUpdateView, \
    MarcaDeleteView, CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView, \
    PaisListView, PaisCreateView, PaisUpdateView, PaisDeleteView, EstadoListView, EstadoCreateView, \
    EstadoUpdateView, EstadoDeleteView, MunicipioListView, MunicipioCreateView, MunicipioUpdateView, \
    MunicipioDeleteView, ProdutoListView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView, \
    ContatoListView, ContatoCreateView, ContatoUpdateView, ContatoDeleteView, municipios, FormaPagamentoListView, \
    FormaPagamentoDeleteView, FormaPagamentoCreateView, FormaPagamentoUpdateView, CondicaoPagamentoListView, \
    CondicaoPagamentoCreateView, CondicaoPagamentoUpdateView, CondicaoPagamentoDeleteView, consulta_cep, consulta_cnpj
        

urlpatterns = [
    path('api/municipios/<int:estado>', municipios),
    path('api/consulta/cep/<str:cep>', consulta_cep),
    path('api/consulta/cnpj/<str:cnpj>', consulta_cnpj),

    path("condicaopagamentos/", CondicaoPagamentoListView.as_view(), name="condicaopagamento-list"),
    path("condicaopagamentos/create", CondicaoPagamentoCreateView.as_view(), name="condicaopagamento-create"),
    path("condicaopagamentos/<int:pk>/update/", CondicaoPagamentoUpdateView.as_view(), name="condicaopagamento-update"),
    path("condicaopagamentos/<int:pk>/delete/", CondicaoPagamentoDeleteView.as_view(), name="condicaopagamento-delete"),

    path("formapagamentos/", FormaPagamentoListView.as_view(), name="formapagamento-list"),
    path("formapagamentos/create", FormaPagamentoCreateView.as_view(), name="formapagamento-create"),
    path("formapagamentos/<int:pk>/update/", FormaPagamentoUpdateView.as_view(), name="formapagamento-update"),
    path("formapagamentos/<int:pk>/delete/", FormaPagamentoDeleteView.as_view(), name="formapagamento-delete"),

    path("contatos/", ContatoListView.as_view(), name="contato-list"),
    path("contatos/create", ContatoCreateView.as_view(), name="contato-create"),
    path("contatos/<int:pk>/update/", ContatoUpdateView.as_view(), name="contato-update"),
    path("contatos/<int:pk>/delete/", ContatoDeleteView.as_view(), name="contato-delete"),

    path("produtos/", ProdutoListView.as_view(), name="produto-list"),
    path("produtos/create", ProdutoCreateView.as_view(), name="produto-create"),
    path("produtos/<int:pk>/update/", ProdutoUpdateView.as_view(), name="produto-update"),
    path("produtos/<int:pk>/delete/", ProdutoDeleteView.as_view(), name="produto-delete"),

    path("municipios/", MunicipioListView.as_view(), name="municipio-list"),
    path("municipios/create", MunicipioCreateView.as_view(), name="municipio-create"),
    path("municipios/<int:pk>/update/", MunicipioUpdateView.as_view(), name="municipio-update"),
    path("municipios/<int:pk>/delete/", MunicipioDeleteView.as_view(), name="municipio-delete"),

    path("estados/", EstadoListView.as_view(), name="estado-list"),
    path("estados/create", EstadoCreateView.as_view(), name="estado-create"),
    path("estados/<int:pk>/update/", EstadoUpdateView.as_view(), name="estado-update"),
    path("estados/<int:pk>/delete/", EstadoDeleteView.as_view(), name="estado-delete"),

    path("pais/", PaisListView.as_view(), name="pais-list"),
    path("pais/create", PaisCreateView.as_view(), name="pais-create"),
    path("pais/<int:pk>/update/", PaisUpdateView.as_view(), name="pais-update"),
    path("pais/<int:pk>/delete/", PaisDeleteView.as_view(), name="pais-delete"),

    path("categorias/", CategoriaListView.as_view(), name="categoria-list"),
    path("categorias/create", CategoriaCreateView.as_view(), name="categoria-create"),
    path("categorias/<int:pk>/update/", CategoriaUpdateView.as_view(), name="categoria-update"),
    path("categorias/<int:pk>/delete/", CategoriaDeleteView.as_view(), name="categoria-delete"),

    path("marcas/", MarcaListView.as_view(), name="marca-list"),
    path("marcas/create", MarcaCreateView.as_view(), name="marca-create"),
    path("marcas/<int:pk>/update/", MarcaUpdateView.as_view(), name="marca-update"),
    path("marcas/<int:pk>/delete/", MarcaDeleteView.as_view(), name="marca-delete"),

    path("unidades/", UnidadeListView.as_view(), name="unidade-list"),
    path("unidades/create", UnidadeCreateView.as_view(), name="unidade-create"),
    path("unidades/<int:pk>/update/", UnidadeUpdateView.as_view(), name="unidade-update"),
    path("unidades/<int:pk>/delete/", UnidadeDeleteView.as_view(), name="unidade-delete"),
]

erp_kronos/urls.py
from django.contrib import admin
from django.urls import path, include
from cadastro.views import Home
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from erp_kronos import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='auth_logout'),
    path('', Home.as_view(), name='Home'),
    path('', include('cadastro.urls')),
    path('', include('financeiro.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financeiro/urls.py
from django.urls import path
from financeiro.views import (ContaReceberListView, ContaReceberCreateView, ContaReceberUpdateView,
                              ContaReceberDeleteView, BaixarContaReceberView, EstornarContaReceberView,
                              ContaPagarListView, ContaPagarCreateView, ContaPagarUpdateView, ContaPagarDeleteView,
                              BaixarContaPagarView, EstornarContaPagarView, FluxoCaixaView, ListaBaixaPagarView, ListaBaixaReceberView)

urlpatterns = [
    # Contas a pagar
    path("contapagars/", ContaPagarListView.as_view(), name="contapagar-list"),
    path("contapagars/create", ContaPagarCreateView.as_view(), name="contapagar-create"),
    path("contapagars/<int:pk>/update/", ContaPagarUpdateView.as_view(), name="contapagar-update"),
    path("contapagars/<int:pk>/delete/", ContaPagarDeleteView.as_view(), name="contapagar-delete"),
    path("baixapagars/<int:contapagar>/baixar", BaixarContaPagarView.as_view(), name="baixapagar-baixar"),
    path("baixapagars/<int:contapagar>/estornar", EstornarContaPagarView.as_view(), name="baixapagar-estornar"),
    path("baixapagars/<int:contapagar>/baixas", ListaBaixaPagarView.as_view(), name="baixapagar-baixas"),
    

    # Contas a receber
    path("contarecebers/", ContaReceberListView.as_view(), name="contareceber-list"),
    path("contarecebers/create", ContaReceberCreateView.as_view(), name="contareceber-create"),
    path("contarecebers/<int:pk>/update/", ContaReceberUpdateView.as_view(), name="contareceber-update"),
    path("contarecebers/<int:pk>/delete/", ContaReceberDeleteView.as_view(), name="contareceber-delete"),
    path("baixarecebers/<int:contareceber>/baixar", BaixarContaReceberView.as_view(), name="baixareceber-baixar"),
    path("baixarecebers/<int:contareceber>/estornar", EstornarContaReceberView.as_view(), name="baixareceber-estornar"),
    path("baixarecebers/<int:contareceber>/baixas", ListaBaixaReceberView.as_view(), name="baixareceber-baixas"),
    # fluxo de caixa
    path("fluxopagamentos/", FluxoCaixaView.as_view(), name="fluxopagamentos-list"),
]

financeiro/models.py
from financeiro.Models.ContaReceberModel import ContaReceber
from financeiro.Models.BaixaReceberModel import BaixaReceber
from financeiro.Models.ContaPagarModel import ContaPagar
from financeiro.Models.BaixaPagarModel import BaixaPagar

venda/models.py
from django.db import models
from core.models import GenericoModel
from cadastro.models import Contato
from django.contrib.auth.models import User
from venda.choices import SituacaoPedido
from cadastro.models import Produto, CondicaoPagamento


class Pedido(GenericoModel):
    numero = models.CharField('Numero', max_length=20, null=True, blank=True)
    data_emissao = models.DateField('Data Emissão')
    contato = models.ForeignKey(Contato, on_delete=models.CASCADE, verbose_name='Cliente')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuário')
    valor_desconto = models.DecimalField('Vlr. Desconto', max_digits=15, decimal_places=2, default=0)
    percentual_desconto = models.DecimalField('Pc. Desconto', max_digits=5, decimal_places=2, default=0)
    valor_total = models.DecimalField('Total', max_digits=15, decimal_places=2)
    observacao = models.CharField('Obs:', max_length=1000, null=True, blank=True)
    situacao = models.IntegerField('Situação', choices=SituacaoPedido.choices, default=SituacaoPedido.ORCAMENTO)

    def __str__(self):
        return self.numero


class PedidoItem(GenericoModel):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, verbose_name='Pedido')
    produto = models.ForeignKey(Produto, on_delete=models.RESTRICT, verbose_name='Produto')
    quantidade = models.DecimalField('Quantdade', max_digits=18, decimal_places=4, default=0)
    valor_unitario = models.DecimalField('Vlr. Unitário', max_digits=15, decimal_places=2, default=0)
    valor_desconto = models.DecimalField('Vlr. Desconto', max_digits=15, decimal_places=2, default=0)
    percentual_desconto = models.DecimalField('Pc. Desconto', max_digits=5, decimal_places=2, default=0)
    total = models.DecimalField('Total', max_digits=15, decimal_places=2, default=0)
    info_adicional = models.CharField('Inf. Adicional', max_length=500, null=True, blank=True)

    def __str__(self) -> str:
        return f'Pedido: {self.pedido.id} - Item: {self.pk}'


class PedidoPagamento(GenericoModel):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, verbose_name='Pedido')
    condicaopagamento = models.ForeignKey(CondicaoPagamento, on_delete=models.RESTRICT,
                                          verbose_name='Condição Pagamento')
    data_vencimento = models.DateField('Data Vencto')
    valor_parcela = models.DecimalField('Valor Parcela', max_digits=15, decimal_places=2, default=0)

    def __str__(self) -> str:
        return f'Número: {self.pk} - Pedido: {self.pedido.pk}'
    

financeiro/forms.py
from core.forms import *
from financeiro.models import ContaReceber, BaixaReceber, ContaPagar, BaixaPagar


class ContaReceberForm(forms.ModelForm):
    class Meta:
        model = ContaReceber
        fields = ['documento', 'parcela', 'contato', 'data_emissao', 'data_vencimento', 'valor_titulo', 'observacao',
                  'situacao']
        widgets = {
            'documento': TextInputBootstrap(attrs={'autofocus': 'true'}),
            'parcela': NumberInputBootstap(),
            'contato': SelectBootstrap(),
            'data_emissao': DateInputBootstrap(format='%Y-%m-%d'),
            'data_vencimento': DateInputBootstrap(format='%Y-%m-%d'),
            'valor_titulo': NumberInputBootstap(),
            'observacao': TextareaInputBootstrap(),
            'situacao': SelectBootstrap()
        }


class BaixaReceberForm(forms.ModelForm):
    class Meta:
        model = BaixaReceber
        fields = ['contareceber', 'formapagamento', 'valor_juros', 'valor_multa', 'valor_desconto', 'valor_pago',
                  'data_baixa']
        widgets = {
            'contareceber': SelectBootstrap(),
            'formapagamento': SelectBootstrap(),
            'valor_juros': NumberInputBootstap(),
            'valor_multa': NumberInputBootstap(),
            'valor_desconto': NumberInputBootstap(),
            'valor_pago': NumberInputBootstap(attrs={'autofocus': 'true'}),
            'data_baixa': DateInputBootstrap(format='%Y-%m-%d'),
        }


class ContaPagarForm(forms.ModelForm):
    class Meta:
        model = ContaPagar
        fields = ['documento', 'parcela', 'contato', 'data_emissao', 'data_vencimento', 'valor_titulo', 'observacao',
                  'situacao']
        widgets = {
            'documento': TextInputBootstrap(attrs={'autofocus': 'true'}),
            'parcela': NumberInputBootstap(),
            'contato': SelectBootstrap(),
            'data_emissao': DateInputBootstrap(format='%Y-%m-%d'),
            'data_vencimento': DateInputBootstrap(format='%Y-%m-%d'),
            'valor_titulo': NumberInputBootstap(),
            'observacao': TextareaInputBootstrap(),
            'situacao': SelectBootstrap()
        }


class BaixaPagarForm(forms.ModelForm):
    class Meta:
        model = BaixaPagar
        fields = ['contapagar', 'formapagamento', 'valor_juros', 'valor_multa', 'valor_desconto', 'valor_pago',
                  'data_baixa']
        widgets = {
            'contapagar': SelectBootstrap(),
            'formapagamento': SelectBootstrap(),
            'valor_juros': NumberInputBootstap(),
            'valor_multa': NumberInputBootstap(),
            'valor_desconto': NumberInputBootstap(),
            'valor_pago': NumberInputBootstap(attrs={'autofocus': 'true'}),
            'data_baixa': DateInputBootstrap(format='%Y-%m-%d'),
        }

financeiro/views.py
from financeiro.Views.ContaReceberView import (ContaReceberListView, ContaReceberCreateView, ContaReceberUpdateView,
                                               ContaReceberDeleteView)
from financeiro.Views.ContaPagarView import (ContaPagarListView, ContaPagarCreateView, ContaPagarUpdateView,
                                             ContaPagarDeleteView)

from financeiro.Views.BaixaReceberView import BaixarContaReceberView, EstornarContaReceberView, ListaBaixaReceberView
from financeiro.Views.BaixaPagarView import BaixarContaPagarView, EstornarContaPagarView, ListaBaixaPagarView
from financeiro.Views.FluxoView import FluxoCaixaView

financeiro/templates/financeiro/contareceber/confirm_delete.html
{% extends 'base.html' %}
{% block title %} {{ verbose_name }} {% endblock title %}
{% block conteudo %}
    
    <form class="mt-5 " method="post"> 
        {% csrf_token %}
        <div class="form-row d-flex justify-content-center">
            <div class="col-6">

                <div class="card shadow card-outline">
                    <div class="card-header">
                        Confirmação de remoção
                    </div>

                    <div class="card-body">
                        <label>Deseja realmente remover <strong>{{ object }}</strong> ?</label>
                    </div>
                
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-danger"><i class="bi bi-check-lg"></i> Confirmar</button>
                        <a class="btn btn-sm btn-secondary" href="{% url 'contareceber-list' %}"><i class="bi bi-reply"></i> Voltar</a>
                    </div>
                
                </div>
            </div>
        </div>

    </form>
    
   
{% endblock conteudo%}

financeiro/templates/financeiro/contareceber/filtro.html
<div class="row">
    <div class="col-auto">
        <div class="dropdown">
            <button class="btn btn-sm  btn-secondary dropdown-toggle"
                    type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">{% if situacao_aberto or situacao_pago_parcial or situacao_pago_total %}<span>●</span>{%endif%} Situação
            </button>

            <div style="width: 11rem" class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
                <div class="form-check">
                    <label class="form-check-label" >Aberto</label>
                    <input class="form-check-input" type="checkbox" name="situacao_aberto" {% if situacao_aberto is not None %}checked{%endif%} >
                </div>

                <div class="form-check">
                    <label class="form-check-label" >Pago Parcial</label>
                    <input class="form-check-input" type="checkbox" name="situacao_pago_parcial" {% if situacao_pago_parcial is not None %}checked{%endif%}>
                </div>

                <div class="form-check">
                    <label class="form-check-label" >Pago Total</label>
                    <input class="form-check-input" type="checkbox" name="situacao_pago_total" {% if situacao_pago_total is not None %}checked{%endif%}>
                </div>

            </div>
        </div>
    </div>

    <div class="col-auto">
    <div class="dropdown">
        <button   class="btn btn-sm btn-secondary dropdown-toggle"
                type="button" data-bs-toggle="dropdown"
                aria-expanded="false">{% if emissao_inicial or emissao_final or vencto_inicial or vencto_final %}<span>●</span>{%endif%} Período</button>
        <div style="width: 11rem" class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
             <div class="row">
                <div class="col-12" >
                    <label for="emissao_inicial">Emissão Inicial</label>
                    <input type="date" id="emissao_inicial" name="emissao_inicial" value="{{ emissao_inicial }}" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-12" >
                    <label for="emissao_final">Emissão Final</label>
                    <input type="date" id="emissao_final" name="emissao_final" value="{{ emissao_final }}" class="form-control form-control-sm" />
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-12" >
                    <label for="vencto_inicial">Vecto Inicial</label>
                    <input type="date" id="vencto_inicial" name="vencto_inicial" value="{{ vencto_inicial }}" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-12" >
                    <label for="vencto_final">Vecto Final</label>
                    <input type="date" id="vencto_final" name="vencto_final" value="{{ vencto_final }}" class="form-control form-control-sm" />
                </div>
            </div>

        </div>
    </div>
    </div>
    {% comment %} <div class="col-4">
        <div class="mb-3">
            <input class="form-control" type="date" name="data_inicial" value="{{ data_inicial }}"/>
        </div>
    </div>
    <div class="col-4">
        <div class="mb-3">
            <input class="form-control" type="date" name="data_final" value="{{ data_final }}" />
        </div>
    </div>  {% endcomment %}
</div>

financeiro/templates/financeiro/contareceber/form.html
{% extends 'base.html' %}
{% block title %} {{ verbose_name }} {% endblock title %}
{% block conteudo %}

<form method="post" novalidate>
    <div class="card shadow card-outline">
        <div class="card-header">
            <div class="row d-flex align-items-center">
                <div class="col">
                    <button class="text-white btn-sm btn bg-success bg-gradient" type="submit" ><i class="bi bi-save"></i> Salvar</button>
                    <a class="text-white btn btn-sm  bg-secondary bg-gradient" href="{% url 'contareceber-list' %}"><i class="bi bi-reply"></i> Voltar</a>
                </div>

                <div class="col-auto">
                    <h4 class="card-title">{%if object %} Editar {% else %} Novo {%endif%} {{ verbose_name }}</h4>
                </div>
            </div>
        </div>

        <div class="card-body">
                    {% csrf_token %}
            <div class="row">

                <div class="col-md-2">
                    <div class="mb-3">
                        {{ form.documento.label_tag }}
                        {{ form.documento }} 

                        {%if form.documento.help_text is not None %}
                            <span class="helptext">{{ form.documento.help_text}}</span>
                        {%endif%}

                        {% if form.errors.documento is not None %}
                            {{ form.errors.documento }}
                        {%endif%}
                    </div>
                </div>

                <div class="col-md-1">
                    <div class="mb-3">
                        {{ form.parcela.label_tag }}
                        {{ form.parcela }} 

                        {%if form.parcela.help_text is not None %}
                            <span class="helptext">{{ form.parcela.help_text}}</span>
                        {%endif%}

                        {% if form.errors.parcela is not None %}
                            {{ form.errors.parcela }}
                        {%endif%}
                    </div>
                </div>

                <div class="col-md-9">
                    <div class="mb-3">
                        <label for="{{form.contato.id_for_label}}">{{form.contato.label}}</label>
                        {{ form.contato.label_tag }}
                        {{ form.contato }} 
                        
                        {%if form.contato.help_text  %}
                            <span class="helptext">{{ form.contato.help_text}}</span>
                        {%endif%}

                        {% if form.errors.contato is not None %}
                            {{ form.errors.contato }}
                        {%endif%}
                    </div>
                </div>

            </div>

            <div class="row">
                
                <div class="col-md-2">
                    <div class="mb-3">
                        {{ form.data_emissao.label_tag }}
                        {{ form.data_emissao }} 

                        {%if form.data_emissao.help_text is not None %}
                            <span class="helptext">{{ form.data_emissao.help_text}}</span>
                        {%endif%}

                        {% if form.errors.data_emissao is not None %}
                            {{ form.errors.data_emissao }}
                        {%endif%}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="mb-3">
                        {{ form.data_vencimento.label_tag }}
                        {{ form.data_vencimento }} 

                        {%if form.data_vencimento.help_text is not None %}
                            <span class="helptext">{{ form.data_vencimento.help_text}}</span>
                        {%endif%}

                        {% if form.errors.data_vencimento is not None %}
                            {{ form.errors.data_vencimento }}
                        {%endif%}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="mb-3">
                        {{ form.valor_titulo.label_tag }}
                        {{ form.valor_titulo }} 

                        {%if form.valor_titulo.help_text is not None %}
                            <span class="helptext">{{ form.valor_titulo.help_text}}</span>
                        {%endif%}

                        {% if form.errors.valor_titulo is not None %}
                            {{ form.errors.valor_titulo }}
                        {%endif%}
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        {{ form.observacao.label_tag }}
                        {{ form.observacao }}

                        {%if form.observacao.help_text is not None %}
                            <span class="helptext">{{ form.observacao.help_text}}</span>
                        {%endif%}

                        {% if form.errors.observacao is not None %}
                            {{ form.errors.observacao }}
                        {%endif%}
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

            
{% endblock conteudo%}

financeiro/templates/financeiro/contareceber/list.html
{% extends 'base.html' %}
{% block title %} {{ verbose_name }} {% endblock title %}
{% block conteudo %}
{% load filtros %}
    <div class="card shadow card-outline mb-1">
        <div class="card-header" style="">
            <form  method="get">
                <div class="row d-flex justify-content-between ">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-8 ">
                                <div class="mb-3">
                                    <div class="input-group ">
                                        <input placeholder="Documento, Nome do Cliente e CPF/CNPJ" autofocus name="search" id="search" class="form-control form-control-sm" type="search" value="{{ search }}">
                                        <button type="submit" class="btn btn-sm btn-secondary"><i class="bi bi-search"></i> Pesquisar</button>
                                    </div>
                                </div>
                            </div>
                            {% if search or emissao_inicial or emissao_final or vencto_inicial or vencto_final or situacao_aberto or situacao_pago_parcial or situacao_pago_total %}
                            <div class="col-md-4 align-self-center">
                                <div class="mb-3">
                                    <a class="btn btn-sm btn-danger" href="{% url 'contareceber-list' %}"><i class="bi bi-trash"></i> Limpar</a>
                                </div>
                            </div>
                            {%endif%}
                        </div>
                    </div>
                    <div class="col-md-auto "> {% include "financeiro/contareceber/filtro.html" %} </div>
                </div>
            </form>
        </div>
        <div class="card-body" style="padding: .5rem .7rem">
            
            <div class="row mb-2">
                <div class="col-auto ">
                    {% if perms.cadastro.add_contareceber %}
                    <a class="btn btn-sm btn-primary " href="{% url 'contareceber-create' %}" ><i class="bi bi-plus-circle"></i>  {{ verbose_name }}</a>
                    {% endif %}
                </div>

                <div class="col text-center align-self-center ">
                    <h5 class="text-muted" style="margin-bottom: 1px">Lista de {{ verbose_name_plural }} </h5>
                </div>
                
            </div>
            
            <div class="table-responsive-sm">
            
                <table class="table mb-1 table-sm table-bordered table-hover caption-top">
                    
                        <thead class="table-secondary ">
                            <tr>
                                <th class="text-center" style="width: 4rem">Ações</th>
                                <th style="width: 10rem">Documento</th>
                                <th>Nome do Cliente</th>
                                <th class="text-center" style="width: 7rem">Data Emissão</th>
                                <th class="text-center" style="width: 7rem">Data Vencto</th>
                                <th style="width: 7rem" class="text-end">Valor</th>
                                <th style="width: 7rem" class="text-end">Saldo Pagar</th>
                                <th style="width: 7rem" class="text-end">Total Pago</th>
                                <th class="text-center">Situação</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for m in object_list %}
                                    <tr  class="{% if m.situacao == 2 %} titulo-pago {%endif%}">
                                        <td class="text-center ">
                                        <div class="btn-group d-grid">
                                            <button  class="btn btn-secondary btn-sm dropdown-toggle option-button" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="bi bi-list-ul"></i>
                                            </button>
                                            <ul class="dropdown-menu">
                                            {% if perms.cadastro.change_contareceber %}
                                                    <li><a class="dropdown-item" href="{% url 'contareceber-update' m.pk %}"><i class="text-primary bi bi-pencil" ></i> Editar</a></li>
                                                {%endif%}

                                                {% if perms.cadastro.delete_contareceber %}
                                                    <li><a class="dropdown-item" href="{% url 'contareceber-delete' m.pk %}"><i class="text-danger bi bi-trash3"></i> Remover</a></li>
                                                {%endif%}
                                                {% if perms.cadastro.add_baixareceber %}
                                                    <li><a class="dropdown-item" href="{% url 'baixareceber-baixar' m.pk %}"><i class="text-success bi bi-cash-stack"></i> Baixar</a></li>
                                                {%endif%}

                                                {% if perms.cadastro.delete_baixareceber %}
                                                    <li><a class="dropdown-item" href="{% url 'baixareceber-estornar' m.pk %}"><i class="text-danger bi bi-arrow-counterclockwise"></i> Estornar</a></li>
                                                {%endif%}

                                                {% if perms.financeiro.view_baixareceber %}
                                                    <li><a class="dropdown-item" href="{% url 'baixareceber-baixas' m.pk %}{% page_current request %}"><i class="text-primary bi bi-eye"></i> Ver Baixas</a></li>
                                                {%endif%}
                                            </ul>
                                        </div>
                                    </td>
                                    <td>{{ m.documento }}</td>
                                    <td>{{ m.contato }}</td>
                                    <td class="text-center" >{{ m.data_emissao }}</td>
                                    <td class="text-center {% if m.vencido == True %}text-danger{% endif %} ">{% if m.vencido == True %}<span class="text-danger">●</span>{% endif %} {{ m.data_vencimento }}</td>
                                    <td class="text-end">{{ m.valor_titulo }}</td>
                                    <td class="text-end">{{ m.saldo_pagar }}</td>
                                    <td class="text-end">{{ m.total_pago }}</td>
                                    <td class="text-center {% if m.situacao != 1 %} text-primary {%endif%} ">{{ m.get_situacao_display }}</td>

                                </tr>
                            {% empty %}
                            <tr>
                                <td class="text-center" colspan="9">Sem registro</td>
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                {% include 'paginate.html' %}
                </div>
        </div>
    </div>
{% endblock conteudo%}